name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - '.github/*'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0.6
          body: |-
            ### ::: softcommerce/module-fakeentitycreator [1.0.6]
            - **Compatibility**: Compatibility with Magento 2.4.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
